import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#0a0a0a',
  },
  webview: {
    flex: 1,
    backgroundColor: '#0a0a0a',
  },
  controls: {
    position: 'absolute',
    top: 10,
    right: 10,
    flexDirection: 'row',
    gap: 8,
    zIndex: 1000,
  },
  button: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 12,
    backgroundColor: 'rgba(17, 24, 39, 0.95)',
    borderWidth: 1,
    gap: 6,
    elevation: 4,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
  },
  buttonPrimary: {
    borderColor: 'rgba(139, 92, 246, 0.4)',
  },
  buttonSuccess: {
    borderColor: 'rgba(16, 185, 129, 0.4)',
  },
  buttonDanger: {
    borderColor: 'rgba(239, 68, 68, 0.4)',
  },
  buttonDisabled: {
    opacity: 0.5,
  },
  buttonIcon: {
    marginRight: 2,
  },
  buttonText: {
    color: '#f9fafb',
    fontSize: 13,
    fontWeight: '600',
  },
  fabButton: {
    position: 'absolute',
    bottom: 20,
    right: 20,
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: '#8b5cf6',
    alignItems: 'center',
    justifyContent: 'center',
    elevation: 6,
    shadowColor: '#8b5cf6',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.4,
    shadowRadius: 8,
    zIndex: 1000,
  },
  fabButtonDisabled: {
    opacity: 0.5,
    backgroundColor: '#6b7280',
  },
  status: {
    position: 'absolute',
    top: 10,
    left: 10,
    backgroundColor: 'rgba(17, 24, 39, 0.95)',
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: 'rgba(139, 92, 246, 0.3)',
    gap: 4,
    zIndex: 1000,
  },
  statusRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  statusText: {
    fontSize: 12,
    color: '#9ca3af',
    fontWeight: '600',
  },
  statusReady: {
    color: '#10b981',
  },
  currentSaveText: {
    fontSize: 11,
    color: '#d1d5db',
    fontWeight: '500',
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.7)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  modalContent: {
    width: '100%',
    maxWidth: 400,
    maxHeight: '80%',
    backgroundColor: '#1a1d29',
    borderRadius: 20,
    padding: 20,
    borderWidth: 1,
    borderColor: 'rgba(139, 92, 246, 0.3)',
    elevation: 10,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.5,
    shadowRadius: 20,
  },
  nodePickerContent: {
    width: '100%',
    maxWidth: 400,
    maxHeight: '70%',
    backgroundColor: '#1a1d29',
    borderRadius: 20,
    padding: 20,
    borderWidth: 1,
    borderColor: 'rgba(139, 92, 246, 0.3)',
    elevation: 10,
  },
  modalTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    marginBottom: 16,
  },
  modalTitle: {
    fontSize: 22,
    fontWeight: '700',
    color: '#f9fafb',
  },
  nodePickerSubtitle: {
    fontSize: 14,
    color: '#9ca3af',
    marginBottom: 16,
  },
  nodeTypesList: {
    maxHeight: 350,
  },
  nodeTypeItem: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 14,
    backgroundColor: 'rgba(31, 41, 55, 0.6)',
    borderRadius: 12,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: 'rgba(139, 92, 246, 0.2)',
    gap: 12,
  },
  nodeTypeIconContainer: {
    width: 48,
    height: 48,
    borderRadius: 12,
    backgroundColor: 'rgba(139, 92, 246, 0.1)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  nodeTypeInfo: {
    flex: 1,
  },
  nodeTypeName: {
    fontSize: 15,
    fontWeight: '600',
    color: '#f9fafb',
    marginBottom: 2,
  },
  nodeTypeDescription: {
    fontSize: 12,
    color: '#9ca3af',
  },
  closePickerButton: {
    marginTop: 16,
    padding: 14,
    backgroundColor: 'rgba(75, 85, 99, 0.6)',
    borderRadius: 12,
    alignItems: 'center',
  },
  closePickerButtonText: {
    color: '#f9fafb',
    fontSize: 15,
    fontWeight: '600',
  },
  newSaveButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 14,
    backgroundColor: 'rgba(16, 185, 129, 0.15)',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: 'rgba(16, 185, 129, 0.3)',
    marginBottom: 16,
    gap: 8,
  },
  newSaveIcon: {
    marginRight: 4,
  },
  newSaveButtonText: {
    color: '#10b981',
    fontSize: 15,
    fontWeight: '600',
  },
  newSaveInputContainer: {
    marginBottom: 16,
  },
  input: {
    backgroundColor: 'rgba(31, 41, 55, 0.8)',
    borderWidth: 1,
    borderColor: 'rgba(139, 92, 246, 0.4)',
    borderRadius: 10,
    padding: 12,
    color: '#f9fafb',
    fontSize: 14,
    marginBottom: 10,
  },
  inputButtons: {
    flexDirection: 'row',
    gap: 8,
  },
  inputButton: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 10,
    borderRadius: 10,
    gap: 6,
  },
  inputButtonCancel: {
    backgroundColor: 'rgba(75, 85, 99, 0.4)',
    borderWidth: 1,
    borderColor: 'rgba(156, 163, 175, 0.3)',
  },
  inputButtonConfirm: {
    backgroundColor: 'rgba(16, 185, 129, 0.15)',
    borderWidth: 1,
    borderColor: 'rgba(16, 185, 129, 0.4)',
  },
  inputButtonText: {
    color: '#f9fafb',
    fontSize: 13,
    fontWeight: '600',
  },
  savesList: {
    maxHeight: 350,
  },
  saveItem: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 12,
    backgroundColor: 'rgba(31, 41, 55, 0.6)',
    borderRadius: 12,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: 'rgba(139, 92, 246, 0.2)',
  },
  saveItemActive: {
    backgroundColor: 'rgba(139, 92, 246, 0.15)',
    borderColor: 'rgba(139, 92, 246, 0.5)',
  },
  saveItemContent: {
    flex: 1,
  },
  saveNameRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginBottom: 4,
  },
  checkIcon: {
    marginRight: 2,
  },
  saveName: {
    fontSize: 15,
    fontWeight: '600',
    color: '#f9fafb',
  },
  saveDateRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  saveDate: {
    fontSize: 11,
    color: '#9ca3af',
  },
  deleteButton: {
    padding: 8,
    borderRadius: 8,
  },
  emptyText: {
    textAlign: 'center',
    color: '#6b7280',
    fontSize: 14,
    fontStyle: 'italic',
    paddingVertical: 40,
  },
  closeButton: {
    marginTop: 16,
    padding: 14,
    backgroundColor: 'rgba(75, 85, 99, 0.6)',
    borderRadius: 12,
    alignItems: 'center',
  },
  closeButtonText: {
    color: '#f9fafb',
    fontSize: 15,
    fontWeight: '600',
  },
  signalControls: {
    bottom: 130,
  },
  buttonWarning: {
    borderColor: 'rgba(251, 191, 36, 0.4)',
    backgroundColor: 'rgba(251, 191, 36, 0.2)',
  },
  buttonSecondary: {
    borderColor: 'rgba(75, 85, 99, 0.4)',
    backgroundColor: 'rgba(75, 85, 99, 0.2)',
  },
  buttonInfo: {
    borderColor: 'rgba(59, 130, 246, 0.4)',
    backgroundColor: 'rgba(59, 130, 246, 0.2)',
  },
  statusWarningText: {
    color: '#fbbf24',
  },
});

export default styles;
