import { StyleSheet } from 'react-native';
import type { AppTheme } from '../theme';
import { hexToRgba } from '../theme';

export const createStyles = (theme: AppTheme) =>
  StyleSheet.create({
    modalOverlay: {
      flex: 1,
      backgroundColor: theme.colors.overlay,
      justifyContent: 'center',
      alignItems: 'center',
    },
    modalContent: {
      backgroundColor: theme.colors.surface,
      borderRadius: 16,
      padding: 20,
      width: '90%',
      maxWidth: 400,
      maxHeight: '80%',
    },
    modalTitleRow: {
      flexDirection: 'row',
      alignItems: 'center',
      marginBottom: 20,
      gap: 12,
    },
    modalTitle: { fontSize: 24, fontWeight: 'bold', color: theme.colors.text },
    newSaveButton: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: hexToRgba(theme.colors.success, 0.2),
      borderWidth: 1,
      borderColor: hexToRgba(theme.colors.success, 0.45),
      paddingHorizontal: 16,
      paddingVertical: 12,
      borderRadius: 8,
      marginBottom: 16,
      gap: 8,
    },
    newSaveIcon: { marginRight: 4 },
    newSaveButtonText: { color: theme.colors.success, fontSize: 16, fontWeight: '600' },
    newSaveInputContainer: { marginBottom: 16 },
    input: {
      backgroundColor: hexToRgba(theme.colors.inputBackground, theme.mode === 'dark' ? 0.9 : 0.95),
      borderRadius: 8,
      borderWidth: 1,
      borderColor: hexToRgba(theme.colors.border, 0.6),
      paddingHorizontal: 12,
      paddingVertical: 10,
      color: theme.colors.text,
      fontSize: 16,
      marginBottom: 8,
    },
    inputButtons: { flexDirection: 'row', gap: 8 },
    inputButton: {
      flex: 1,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      paddingVertical: 8,
      borderRadius: 6,
      gap: 6,
    },
    inputButtonCancel: { backgroundColor: hexToRgba(theme.colors.border, 0.3) },
    inputButtonConfirm: { backgroundColor: theme.colors.success },
    inputButtonText: { color: theme.colors.text, fontSize: 14, fontWeight: '500' },
    savesList: { maxHeight: 300, marginBottom: 16 },
    emptyText: {
      color: theme.colors.textSecondary,
      fontSize: 16,
      textAlign: 'center',
      paddingVertical: 20,
    },
    saveItem: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: hexToRgba(theme.colors.surface, 0.9),
      borderRadius: 8,
      marginBottom: 8,
      overflow: 'hidden',
      borderWidth: 1,
      borderColor: hexToRgba(theme.colors.border, 0.5),
    },
    saveItemActive: { borderWidth: 2, borderColor: theme.colors.primary },
    saveItemContent: {
      flex: 1,
      padding: 12,
    },
    saveNameRow: {
      flexDirection: 'row',
      alignItems: 'center',
      marginBottom: 4,
      gap: 8,
    },
    checkIcon: {
      marginRight: 4,
    },
    saveName: { color: theme.colors.text, fontSize: 16, fontWeight: '600' },
    saveDateRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
    },
    saveDate: { color: theme.colors.textSecondary, fontSize: 12 },
    deleteButton: {
      padding: 12,
      backgroundColor: 'transparent',
      justifyContent: 'center',
      alignItems: 'center',
    },
    deleteIcon: { color: theme.colors.error, fontSize: 20 },
    closeButton: {
      backgroundColor: theme.colors.chip,
      paddingVertical: 12,
      borderRadius: 8,
      alignItems: 'center',
    },
    closeButtonText: { color: theme.colors.text, fontSize: 16, fontWeight: '600' },
  });

export default createStyles;
