import { StyleSheet } from 'react-native';
import type { AppTheme } from '../styles/theme';
import { hexToRgba } from '../styles/colorUtils';

export const createStyles = (theme: AppTheme) => {
  const translucentSurface = hexToRgba(theme.colors.surface, theme.mode === 'dark' ? 0.94 : 0.9);
  const translucentSecondary = hexToRgba(
    theme.colors.backgroundSecondary,
    theme.mode === 'dark' ? 0.9 : 0.85
  );
  const subtleBorder = hexToRgba(theme.colors.border, 0.7);

  return StyleSheet.create({
    container: { flex: 1, backgroundColor: theme.colors.background },
    webview: { flex: 1, backgroundColor: theme.colors.background },
    controls: {
      position: 'absolute',
      top: 10,
      right: 10,
      flexDirection: 'row',
      gap: 8,
      zIndex: 1000,
    },
    button: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingHorizontal: 14,
      paddingVertical: 8,
      borderRadius: 12,
      backgroundColor: translucentSurface,
      borderWidth: 1,
      borderColor: subtleBorder,
      gap: 6,
      elevation: 4,
      shadowColor: theme.colors.shadow,
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.3,
      shadowRadius: 6,
    },
    buttonPrimary: {
      borderColor: hexToRgba(theme.colors.primary, 0.6),
      backgroundColor: hexToRgba(theme.colors.primary, 0.12),
    },
    buttonSuccess: {
      borderColor: hexToRgba(theme.colors.success, 0.45),
      backgroundColor: hexToRgba(theme.colors.success, 0.15),
    },
    buttonDanger: {
      borderColor: hexToRgba(theme.colors.error, 0.45),
      backgroundColor: hexToRgba(theme.colors.error, 0.15),
    },
    buttonSecondary: {
      borderColor: subtleBorder,
      backgroundColor: hexToRgba(theme.colors.backgroundSecondary, 0.5),
    },
    buttonInfo: {
      borderColor: hexToRgba(theme.colors.secondary, 0.5),
      backgroundColor: hexToRgba(theme.colors.secondary, 0.15),
    },
    buttonWarning: {
      borderColor: hexToRgba(theme.colors.warning, 0.45),
      backgroundColor: hexToRgba(theme.colors.warning, 0.18),
    },
    buttonDisabled: { opacity: 0.5 },
    buttonIcon: { marginRight: 2 },
    buttonText: { color: theme.colors.text, fontSize: 13, fontWeight: '600' },
    fabButton: {
      position: 'absolute',
      bottom: 120,
      right: 16,
      width: 56,
      height: 56,
      borderRadius: 28,
      backgroundColor: theme.colors.primary,
      alignItems: 'center',
      justifyContent: 'center',
      elevation: 6,
      shadowColor: theme.colors.primary,
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.4,
      shadowRadius: 8,
      zIndex: 900,
    },
    fabButtonDisabled: {
      opacity: 0.5,
      backgroundColor: theme.colors.chipDisabled,
    },
    modLibraryButton: {
      position: 'absolute',
      bottom: 120,
      left: 16,
      flexDirection: 'row',
      alignItems: 'center',
      paddingHorizontal: 14,
      paddingVertical: 10,
      borderRadius: 24,
      backgroundColor: theme.colors.secondary,
      elevation: 6,
      shadowColor: theme.colors.secondary,
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.4,
      shadowRadius: 8,
      zIndex: 1000,
      gap: 8,
    },
    modLibraryButtonText: {
      color: '#ffffff',
      fontSize: 14,
      fontWeight: '600',
    },
    status: {
      position: 'absolute',
      top: 10,
      left: 10,
      backgroundColor: translucentSurface,
      paddingHorizontal: 12,
      paddingVertical: 8,
      borderRadius: 10,
      borderWidth: 1,
      borderColor: subtleBorder,
      gap: 4,
      zIndex: 1000,
    },
    statusRow: { flexDirection: 'row', alignItems: 'center', gap: 6 },
    statusText: { fontSize: 12, color: theme.colors.textSecondary, fontWeight: '600' },
    statusReady: { color: theme.colors.success },
    currentSaveText: { fontSize: 11, color: theme.colors.text, fontWeight: '500' },
    statusWarningText: { color: theme.colors.warning },
    modalOverlay: {
      flex: 1,
      backgroundColor: theme.colors.overlay,
      justifyContent: 'center',
      alignItems: 'center',
      padding: 20,
    },
    modalContent: {
      width: '100%',
      maxWidth: 400,
      maxHeight: '80%',
      backgroundColor: theme.colors.surface,
      borderRadius: 20,
      padding: 20,
      borderWidth: 1,
      borderColor: subtleBorder,
      elevation: 10,
      shadowColor: theme.colors.shadow,
      shadowOffset: { width: 0, height: 10 },
      shadowOpacity: 0.5,
      shadowRadius: 20,
    },
    nodePickerContent: {
      width: '100%',
      maxWidth: 400,
      maxHeight: '70%',
      backgroundColor: theme.colors.surface,
      borderRadius: 20,
      padding: 20,
      borderWidth: 1,
      borderColor: subtleBorder,
      elevation: 10,
    },
    modalTitleRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 12,
      marginBottom: 16,
    },
    modalTitle: { fontSize: 22, fontWeight: '700', color: theme.colors.text },
    nodePickerSubtitle: { fontSize: 14, color: theme.colors.textSecondary, marginBottom: 16 },
    nodeTypesList: { maxHeight: 350 },
    nodeTypeItem: {
      flexDirection: 'row',
      alignItems: 'center',
      padding: 14,
      backgroundColor: translucentSecondary,
      borderRadius: 12,
      marginBottom: 10,
      borderWidth: 1,
      borderColor: subtleBorder,
      gap: 12,
    },
    nodeTypeIconContainer: {
      width: 48,
      height: 48,
      borderRadius: 12,
      backgroundColor: hexToRgba(theme.colors.primarySoft, 0.15),
      alignItems: 'center',
      justifyContent: 'center',
    },
    nodeTypeInfo: { flex: 1 },
    nodeTypeName: { fontSize: 15, fontWeight: '600', color: theme.colors.text, marginBottom: 2 },
    nodeTypeDescription: { fontSize: 12, color: theme.colors.textSecondary },
    closePickerButton: {
      marginTop: 16,
      padding: 14,
      backgroundColor: hexToRgba(theme.colors.border, 0.3),
      borderRadius: 12,
      alignItems: 'center',
    },
    closePickerButtonText: { color: theme.colors.text, fontSize: 15, fontWeight: '600' },
    newSaveButton: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      padding: 14,
      backgroundColor: hexToRgba(theme.colors.success, 0.18),
      borderRadius: 12,
      borderWidth: 1,
      borderColor: hexToRgba(theme.colors.success, 0.4),
      marginBottom: 16,
      gap: 8,
    },
    newSaveIcon: { marginRight: 4 },
    newSaveButtonText: { color: theme.colors.success, fontSize: 15, fontWeight: '600' },
    newSaveInputContainer: { marginBottom: 16 },
    input: {
      backgroundColor: hexToRgba(theme.colors.inputBackground, theme.mode === 'dark' ? 0.9 : 1),
      borderWidth: 1,
      borderColor: subtleBorder,
      borderRadius: 10,
      padding: 12,
      color: theme.colors.text,
      fontSize: 14,
      marginBottom: 10,
    },
    inputButtons: { flexDirection: 'row', gap: 8 },
    inputButton: {
      flex: 1,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      padding: 10,
      borderRadius: 10,
      gap: 6,
    },
    inputButtonCancel: {
      backgroundColor: theme.colors.chipDisabled,
      borderWidth: 1,
      borderColor: hexToRgba(theme.colors.border, 0.5),
    },
    inputButtonConfirm: {
      backgroundColor: hexToRgba(theme.colors.success, 0.25),
      borderWidth: 1,
      borderColor: hexToRgba(theme.colors.success, 0.5),
    },
    inputButtonText: { color: theme.colors.text, fontSize: 13, fontWeight: '600' },
    savesList: { maxHeight: 350 },
    saveItem: {
      flexDirection: 'row',
      alignItems: 'center',
      padding: 12,
      backgroundColor: translucentSecondary,
      borderRadius: 12,
      marginBottom: 10,
      borderWidth: 1,
      borderColor: subtleBorder,
    },
    saveItemActive: {
      backgroundColor: hexToRgba(theme.colors.primary, 0.15),
      borderColor: hexToRgba(theme.colors.primary, 0.6),
    },
    saveItemContent: { flex: 1 },
    saveNameRow: { flexDirection: 'row', alignItems: 'center', gap: 6, marginBottom: 4 },
    checkIcon: { marginRight: 2 },
    saveName: { fontSize: 15, fontWeight: '600', color: theme.colors.text },
    saveDateRow: { flexDirection: 'row', alignItems: 'center', gap: 4 },
    saveDate: { fontSize: 11, color: theme.colors.textSecondary },
    deleteButton: { padding: 8, borderRadius: 8 },
    emptyText: {
      textAlign: 'center',
      color: theme.colors.textMuted,
      fontSize: 14,
      fontStyle: 'italic',
      paddingVertical: 40,
    },
    closeButton: {
      marginTop: 16,
      padding: 14,
      backgroundColor: theme.colors.chip,
      borderRadius: 12,
      alignItems: 'center',
    },
    closeButtonText: { color: theme.colors.text, fontSize: 15, fontWeight: '600' },
    permissionBanner: {
      position: 'absolute',
      top: 60,
      left: 10,
      right: 10,
      backgroundColor: hexToRgba(theme.colors.error, 0.95),
      borderRadius: 12,
      borderWidth: 1,
      borderColor: hexToRgba(theme.colors.error, 0.5),
      padding: 12,
      zIndex: 999,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: 12,
      elevation: 8,
      shadowColor: theme.colors.error,
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.3,
      shadowRadius: 8,
    },
    permissionText: { color: theme.colors.text, flex: 1, fontSize: 12 },
    permissionButton: {
      paddingVertical: 8,
      paddingHorizontal: 12,
      backgroundColor: theme.colors.error,
      borderRadius: 8,
    },
    permissionButtonText: { color: theme.colors.background, fontWeight: '700' },
  });
};

export default createStyles;
